name: CastleSiege
main: me.cbhud.Main
author: cbhud
version: 1.0.9
api-version: 1.17
commands:
  cs:
    description: Castle Siege main command
    usage: /<command> <endgame|setlobby|setmobspawn|start|teamspawn>
    permission: viking.admin
  kit:
    description: Manages player kits
    usage: /<command>
  teamjoin:
    description: Join a team
    usage: /<command> <teamName>
    permission: viking.player
