name: CastleSiege
main: me.cbhud.castlesiege.Main
author: cbhud
version: 1.2.1
api-version: 1.17
commands:
  cs:
    description: Castle Siege main command
    usage: /<command> <endgame|setlobby|setmobspawn|start|teamspawn>
    permission: viking.admin
  stats:
    description: Check player stats
    usage: /stats [player]
