name: Vikings
main: me.cbhud.Main
author: cbhud
version: 1.0
api-version: 1.20.2
commands:
  givesoup:
    description: Gives soup
    usage: /<command>
  giveaxe:
    description: Gives soup
    usage: /<command>
  giveblood:
    description: Gives soup
    usage: /<command>