name: CastleSiege
main: me.cbhud.Main
author: cbhud
version: 1.0.7
api-version: 1.17
commands:
  setlobby:
    description: Gives soup
    usage: /<command>
    permission: viking.admin
  start:
    description: Gives soup
    usage: /<command>
    permission: war.start
  teamjoin:
    description: Gives soup
    usage: /<command>
  setspawn:
    description: Gives soup
    usage: /<command>
    permission: viking.admin
  setmobspawn:
    description: mob
    usage: /<command>
    permission: viking.admin
  kit:
    description: kit
    usage: /<command>
  endgame:
    description: kit
    usage: /<command>
    permission: war.start