name: CastleSiege
main: me.cbhud.castlesiege.Main
author: cbhud
version: 1.1.7
api-version: 1.17
commands:
  cs:
    description: Castle Siege main command
    usage: /<command> <endgame|setlobby|setmobspawn|start|teamspawn>
    permission: viking.admin
  kit:
    description: Manages player kits
    usage: /<command>
  stats:
    description: Check player stats
    usage: /stats [player]
