name: CastleSiege
main: me.cbhud.castlesiege.CastleSiege
author: cbhud
version: 1.2.4
api-version: 1.17
commands:
  cs:
    description: Castle Siege main command
    usage: /<command> <endgame|setlobby|setmobspawn|start|teamspawn>
    permission: viking.admin
  stats:
    description: Check player stats
    usage: /stats [player]
  coins:
    description: Manage player coins.
    usage: /coins <set|add|remove> <player> <amount>
    permission: cs.admin
    permission-message: You do not have permission to use this command.
